micronaut:
  application:
    name: apiFilmes
  server:
    port: 8085

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

cassandra:
  default:
    basic:
      contact-points:
        - ${cassandra_contact_points:localhost}
      session-keyspace: ${cassandra_session_keyspace:filmesdb}
      load-balancing-policy:
        local-datacenter: ${cassandra_local_datacenter:datacenter1}






endpoints:
  health:
    enabled: true